### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by aishangfy** [saitjr/STShareTool#2]
- (void)touchesBegan:(NSSet<UITouch *> *)touches withEvent:(UIEvent *)event {
  
  NSDictionary *shareContent = @{STShareContentKey : @"SwiftGG 最帅",
                                 STShareImageKey : [UIImage imageNamed:@"60"],
                                 STShareURLKey : @"http://www.swift.gg"};
  [STShareTool presentShareViewController:shareContent];
  }
  执行后会在main函数crash！

**Comment by saitjr** [comment]
我测试并未发现 crash，能提供更详细的测试步骤吗？测试是模拟器还是真机？真机型号？

**Comment by aishangfy** [comment]
iPad Air，真机和模拟器都会crash，app启动后，点击屏幕后crash，osx 10.11 + xcode 7

**Comment by aishangfy** [comment]
iPhone模拟器正常，iPad模拟器crash

**Comment by saitjr** [comment]
依然没发现...我的环境是 Xcode 7.3    iOS 9.2.1 和 9.3  都试过，均未出现 crash

**Comment by saitjr** [comment]
哦  出现了，正在修改，谢谢

**Comment by saitjr** [comment]
原因是因为  在 iPad 上 activity 必须要装到 popover 中
将默认弹出事件改为了：

```
+ (void)presentShareViewController:(NSDictionary *)shareContent sender:(UIView *)sender;
```

对应实现加上了 ：

```
if ( [activityViewController respondsToSelector:@selector(popoverPresentationController)] ) {
        activityViewController.popoverPresentationController.sourceView = sender.superview;
        activityViewController.popoverPresentationController.sourceRect = sender.frame;
}
```

仓库已更新，更详细的可以直接看 demo

**Comment by aishangfy** [comment]
非常高效，赞！
