### ISSUE TITLE
艾玛

### ISSUE THREAD

**Issue by lilongcnc** [saitjr/STShareTool#3]
这都用了一遍啊!!

**Comment by saitjr** [comment]
啥

**Comment by lilongcnc** [comment]
么事,我开始以为你把所有的常见第三方分享 SDK 都跑了一遍.....捎带把第三方登陆也弄一个出来,这样我就不用自己看该死的文档了

**Comment by lilongcnc** [comment]
么事,我开始以为你把所有的常见第三方分享 SDK 都跑了一遍.....捎带把第三方登陆也弄一个出来,这样我就不用自己看该死的文档了

**Comment by saitjr** [comment]
登录还没时间整呢

**Comment by lilongcnc** [comment]
最近你们公司挺忙的?

**Comment by saitjr** [comment]
很忙

**Comment by lilongcnc** [comment]
我这两天忙着面试别人,iOS的简历真的是海多.....
